# see:
# * https://docs.docker.com/go/compose-spec-reference
# * https://github.com/docker/awesome-compose

# todo:
# * configure caddy as an https terminating proxy for denokv
# * configure caddy as a reverse proxy for the app

name: booru-bot

services:
  denokv:
    image: ghcr.io/denoland/denokv
    restart: unless-stopped
    command: --sqlite-path=/data/denokv.sqlite serve
    env_file:
      - token.env
    expose:
      - 4512
    volumes:
      - data:/data

  server:
    build: .
    restart: unless-stopped
    depends_on:
      - denokv
    env_file:
      - token.env
    expose:
      - 8000

volumes:
  data:
