# see:
# * https://docs.docker.com/go/compose-spec-reference
# * https://github.com/docker/awesome-compose

name: booru-bot

services:
  kv:
    image: ghcr.io/denoland/denokv
    restart: unless-stopped
    environment:
      - DENO_KV_ACCESS_TOKEN=${DENO_KV_ACCESS_TOKEN}
      - DENO_KV_SQLITE_PATH=/data/denokv.sqlite
    ports:
      - 4512:4512
    volumes:
      - data:/data
    command: serve

  server:
    build: .
    restart: unless-stopped
    depends_on:
      - kv
    environment:
      - DENO_KV_ACCESS_TOKEN=${DENO_KV_ACCESS_TOKEN}

volumes:
  data:
